ALTER TABLE author
ALTER COLUMN id TYPE BIGINT;

ALTER TABLE book
ALTER COLUMN id TYPE BIGINT;

ALTER TABLE journal
ALTER COLUMN id TYPE BIGINT;

ALTER TABLE book
    ALTER COLUMN author_id SET DATA TYPE BIGINT;

ALTER TABLE users
ALTER COLUMN id TYPE BIGINT;
